### ISSUE TITLE
Add test(s)

### ISSUE THREAD

**Issue by fedorov** [QIICR/TCIABrowser#32]
There should at least be a test that makes sure TCIA server works as expected.

**Comment by fedorov** [comment]
need to fix currently failing tests as was done here: https://github.com/fedorov/Reporting/commit/f828c4df8ea7cd12bab417336673e8710e686475

**Comment by mehrtash** [comment]
The tests are fixed and all passed in [Mac Os](http://slicer.cdash.org/viewTest.php?onlypassed&buildid=467380). However one of the tests [py_TCIABrowser](http://slicer.cdash.org/testDetails.php?test=6363743&build=467318) failed on my Linux machine due to memory leak. Looks like this one is also failing on factory-south-w Windows machine.

**Comment by mehrtash** [comment]
It looks like the API V1 is now working again.

**Comment by mehrtash** [comment]
All dashboard tests passed today: http://slicer.cdash.org/index.php?project=Slicer4&subproject=TCIABrowser
